config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :administrators

  resources :employees

  resources :parents

  resources :classrooms

  resources :teachers

  resources :students

  resources :people

  resources :students do
		resources :parents
	end

end

app/models/employee.rb
class Employee < Person
  belongs_to :user
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params[:employee]
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.slim
= form_for @employee do |f|
  - if @employee.errors.any?
    #error_explanation
      h2 = "#{pluralize(@employee.errors.count, "error")} prohibited this employee from being saved:"
      ul
        - @employee.errors.full_messages.each do |message|
          li = message

  .actions = f.submit 'Save'

app/views/employees/edit.html.slim
h1 Editing employee

== render 'form'

= link_to 'Show', @employee
'|
= link_to 'Back', employees_path

app/views/employees/index.html.slim
h1 Listing employees

table
  thead
    tr
      th
      th
      th

  tbody
    - @employees.each do |employee|
      tr
        td = link_to 'Show', employee
        td = link_to 'Edit', edit_employee_path(employee)
        td = link_to 'Destroy', employee, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Employee', new_employee_path

app/views/employees/new.html.slim
h1 New employee

== render 'form'

= link_to 'Back', employees_path

app/views/employees/show.html.slim
p#notice = notice


= link_to 'Edit', edit_employee_path(@employee)
'|
= link_to 'Back', employees_path