config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :administrators

  resources :employees

  resources :parents

  resources :classrooms

  resources :teachers

  resources :students

  resources :people

  resources :students do
		resources :parents
	end

end

app/models/person.rb
class Person
  include Mongoid::Document
  field :first_name, type: String
  field :last_name, type: String
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params[:person]
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.slim
= form_for @person do |f|
  - if @person.errors.any?
    #error_explanation
      h2 = "#{pluralize(@person.errors.count, "error")} prohibited this person from being saved:"
      ul
        - @person.errors.full_messages.each do |message|
          li = message

  .actions = f.submit 'Save'

app/views/people/edit.html.slim
h1 Editing person

== render 'form'

= link_to 'Show', @person
'|
= link_to 'Back', people_path

app/views/people/index.html.slim
h1 Listing people

table
  thead
    tr
      th
      th
      th

  tbody
    - @people.each do |person|
      tr
        td = link_to 'Show', person
        td = link_to 'Edit', edit_person_path(person)
        td = link_to 'Destroy', person, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Person', new_person_path

app/views/people/new.html.slim
h1 New person

== render 'form'

= link_to 'Back', people_path

app/views/people/show.html.slim
p#notice = notice


= link_to 'Edit', edit_person_path(@person)
'|
= link_to 'Back', people_path