config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :administrators

  resources :employees

  resources :parents

  resources :classrooms

  resources :teachers

  resources :students

  resources :people

  resources :students do
		resources :parents
	end

end

app/models/teacher.rb
class Teacher < Employee
  belongs_to :classroom
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params[:teacher]
    end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.slim
= form_for @teacher do |f|
  - if @teacher.errors.any?
    #error_explanation
      h2 = "#{pluralize(@teacher.errors.count, "error")} prohibited this teacher from being saved:"
      ul
        - @teacher.errors.full_messages.each do |message|
          li = message

  .actions = f.submit 'Save'

app/views/teachers/edit.html.slim
h1 Editing teacher

== render 'form'

= link_to 'Show', @teacher
'|
= link_to 'Back', teachers_path

app/views/teachers/index.html.slim
h1 Listing teachers

table
  thead
    tr
      th
      th
      th

  tbody
    - @teachers.each do |teacher|
      tr
        td = link_to 'Show', teacher
        td = link_to 'Edit', edit_teacher_path(teacher)
        td = link_to 'Destroy', teacher, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Teacher', new_teacher_path

app/views/teachers/new.html.slim
h1 New teacher

== render 'form'

= link_to 'Back', teachers_path

app/views/teachers/show.html.slim
p#notice = notice


= link_to 'Edit', edit_teacher_path(@teacher)
'|
= link_to 'Back', teachers_path