config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :administrators

  resources :employees

  resources :parents

  resources :classrooms

  resources :teachers

  resources :students

  resources :people

  resources :students do
		resources :parents
	end

end

app/models/administrator.rb
class Administrator < Employee
  field :office, type: Integer
end

app/controllers/administrators_controller.rb
class AdministratorsController < ApplicationController
  before_action :set_administrator, only: [:show, :edit, :update, :destroy]

  # GET /administrators
  # GET /administrators.json
  def index
    @administrators = Administrator.all
  end

  # GET /administrators/1
  # GET /administrators/1.json
  def show
  end

  # GET /administrators/new
  def new
    @administrator = Administrator.new
  end

  # GET /administrators/1/edit
  def edit
  end

  # POST /administrators
  # POST /administrators.json
  def create
    @administrator = Administrator.new(administrator_params)

    respond_to do |format|
      if @administrator.save
        format.html { redirect_to @administrator, notice: 'Administrator was successfully created.' }
        format.json { render :show, status: :created, location: @administrator }
      else
        format.html { render :new }
        format.json { render json: @administrator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /administrators/1
  # PATCH/PUT /administrators/1.json
  def update
    respond_to do |format|
      if @administrator.update(administrator_params)
        format.html { redirect_to @administrator, notice: 'Administrator was successfully updated.' }
        format.json { render :show, status: :ok, location: @administrator }
      else
        format.html { render :edit }
        format.json { render json: @administrator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /administrators/1
  # DELETE /administrators/1.json
  def destroy
    @administrator.destroy
    respond_to do |format|
      format.html { redirect_to administrators_url, notice: 'Administrator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_administrator
      @administrator = Administrator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def administrator_params
      params[:administrator]
    end
end

app/helpers/administrators_helper.rb
module AdministratorsHelper
end

app/views/administrators/_form.html.slim
= form_for @administrator do |f|
  - if @administrator.errors.any?
    #error_explanation
      h2 = "#{pluralize(@administrator.errors.count, "error")} prohibited this administrator from being saved:"
      ul
        - @administrator.errors.full_messages.each do |message|
          li = message

  .actions = f.submit 'Save'

app/views/administrators/edit.html.slim
h1 Editing administrator

== render 'form'

= link_to 'Show', @administrator
'|
= link_to 'Back', administrators_path

app/views/administrators/index.html.slim
h1 Listing administrators

table
  thead
    tr
      th
      th
      th

  tbody
    - @administrators.each do |administrator|
      tr
        td = link_to 'Show', administrator
        td = link_to 'Edit', edit_administrator_path(administrator)
        td = link_to 'Destroy', administrator, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Administrator', new_administrator_path

app/views/administrators/new.html.slim
h1 New administrator

== render 'form'

= link_to 'Back', administrators_path

app/views/administrators/show.html.slim
p#notice = notice


= link_to 'Edit', edit_administrator_path(@administrator)
'|
= link_to 'Back', administrators_path